import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /generational-transfer/  ->  ebook slug 'generational-transfer'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('generational-transfer');
}

export default function Page() {
  return <EbookLanding slug="generational-transfer" />;
}
