import type { Metadata } from 'next';
import SiteGraph from '../graph/SiteGraph';
import graphData from './graph-data.json';

/* Interactive map of the OLD (live WordPress) site's pages and internal links,
   crawled from insuranceandestates.com. Never indexed, not in the sitemap.
   Data: graph-data.json, regenerated by scripts/gen-site-graph-data-old.mjs.
   Node clicks open the LIVE site. */

export const metadata: Metadata = {
  title: { absolute: 'Site Graph (old website) — internal' },
  robots: { index: false, follow: false },
};

export default function Page() {
  return (
    <SiteGraph
      data={graphData as never}
      subtitle="old website (WordPress)"
      linkBase="https://www.insuranceandestates.com"
    />
  );
}
