import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /financial-planning-has-failed/  ->  ebook slug 'financial-planning-has-failed'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('financial-planning-has-failed');
}

export default function Page() {
  return <EbookLanding slug="financial-planning-has-failed" />;
}
