import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /kingdom-money/  ->  ebook slug 'kingdom-money'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('kingdom-money');
}

export default function Page() {
  return <EbookLanding slug="kingdom-money" />;
}
