import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';
import SalesSections from './SalesSections';

/* eBook landing page. Route: /kingdom-money/  ->  ebook slug 'kingdom-money'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour.
   Sales copy below the hero + form lives in ./SalesSections.tsx (live copy,
   verbatim). Title matches live exactly. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('kingdom-money', {
    title: 'Kingdom Money – I&E | Whole Life & Infinite Banking Strategies',
  });
}

export default function Page() {
  return (
    <EbookLanding slug="kingdom-money">
      <SalesSections />
    </EbookLanding>
  );
}
