import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /the-ultimate-asset-ebook/  ->  ebook slug 'the-ultimate-asset'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('the-ultimate-asset');
}

export default function Page() {
  return <EbookLanding slug="the-ultimate-asset" />;
}
