import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /estate-planners-tactical-guide/  ->  ebook slug 'estate-planners-tactical-guide'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('estate-planners-tactical-guide');
}

export default function Page() {
  return <EbookLanding slug="estate-planners-tactical-guide" />;
}
