import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';
import SalesSections from './SalesSections';

/* eBook landing page. Route: /self-banking-blueprint/  ->  ebook slug 'self-banking-blueprint'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour.
   Sales copy below the hero + form lives in ./SalesSections.tsx (live copy,
   verbatim). Title/description match live exactly (the description is live's
   Slim SEO auto-truncated string, kept as-is). */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('self-banking-blueprint', {
    title: 'Self Banking Blueprint – I&E | Whole Life & Infinite Banking Strategies',
    description:
      'Congratulations on Taking a Huge Step Toward Taking Control of Your Wealth Building Plan! The Self Banking Blueprint was developed from collaboration with infin',
  });
}

export default function Page() {
  return (
    <EbookLanding slug="self-banking-blueprint">
      <SalesSections />
    </EbookLanding>
  );
}
