import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /self-banking-blueprint/  ->  ebook slug 'self-banking-blueprint'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('self-banking-blueprint');
}

export default function Page() {
  return <EbookLanding slug="self-banking-blueprint" />;
}
