import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /life-insurance-essentials-report/  ->  ebook slug 'life-insurance-essentials-report'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('life-insurance-essentials-report');
}

export default function Page() {
  return <EbookLanding slug="life-insurance-essentials-report" />;
}
