import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /estate-planning-tactical-checklist/  ->  ebook slug 'estate-planning-tactical-checklist'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('estate-planning-tactical-checklist');
}

export default function Page() {
  return <EbookLanding slug="estate-planning-tactical-checklist" />;
}
