import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /money-secrets/  ->  ebook slug 'money-secrets-of-the-wealthy'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('money-secrets-of-the-wealthy');
}

export default function Page() {
  return <EbookLanding slug="money-secrets-of-the-wealthy" />;
}
