import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';
import SalesSections from './SalesSections';

/* eBook landing page. Route: /intentional-wealth-effect/  ->  ebook slug 'intentional-wealth-effect'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour.
   Sales copy below the hero + form lives in ./SalesSections.tsx (live copy,
   verbatim). Title/description match live exactly (the description is live's
   Slim SEO auto-truncated string, kept as-is). */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('intentional-wealth-effect', {
    title: 'Intentional Wealth Effect – I&E | Whole Life & Infinite Banking Strategies',
    description:
      'Get Your Copy of The Intentional Wealth Effect Get Your Copy Today! If you’re stressed about your finances; let me tell you, my early financial life was anythin',
  });
}

export default function Page() {
  return (
    <EbookLanding slug="intentional-wealth-effect">
      <SalesSections />
    </EbookLanding>
  );
}
