import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /intentional-wealth-effect/  ->  ebook slug 'intentional-wealth-effect'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('intentional-wealth-effect');
}

export default function Page() {
  return <EbookLanding slug="intentional-wealth-effect" />;
}
