import type { Metadata } from 'next';
import EbookLanding, { ebookLandingMetadata } from '../../components/EbookLanding';

/* eBook landing page. Route: /5-important-estate-planning-steps/  ->  ebook slug '5-important-estate-planning-steps'.
   Generated by scripts context; edit EbookLanding.tsx for shared behaviour. */

export const revalidate = 300;

export function generateMetadata(): Promise<Metadata> {
  return ebookLandingMetadata('5-important-estate-planning-steps');
}

export default function Page() {
  return <EbookLanding slug="5-important-estate-planning-steps" />;
}
