import type { Metadata } from 'next';
import SiteGraph from './SiteGraph';

/* Internal interactive map of the site's pages and their real internal links.
   Never indexed, not in the sitemap. Data: graph-data.json, regenerated by
   scripts/gen-site-graph-data.mjs after content/linking changes. */

export const metadata: Metadata = {
  title: { absolute: 'Site Graph — internal' },
  robots: { index: false, follow: false },
};

export default function Page() {
  return <SiteGraph />;
}
