// AUTO-GENERATED by scripts/build-leads.mjs — do not edit by hand.
// AGGREGATES ONLY — contains no names, emails, phones, or record IDs.
// Regenerate after an updated export:  node scripts/build-leads.mjs

export interface LeadSourceStat { source: string; leads: number; customers: number; convRate: number; customerPremium: number; allPremium: number; }
export interface LeadMonthStat {
  key: string; label: string; sortKey: number;
  total: number; organic: number; paidAds: number; other: number;
  customers: number; organicCustomers: number; paidCustomers: number;
  paidPremium: number; organicPremium: number;
}
export interface LeadsData {
  range: string;
  totals: { leads: number; customers: number; convRate: number; customersWithPremium: number; avgCustomerPremium: number; totalCustomerPremium: number; };
  bySource: LeadSourceStat[];
  byMonth: LeadMonthStat[];
  byInterest: { interest: string; leads: number }[];
  byAgent: { agent: string; leads: number; customers: number }[];
}

export const leadsData: LeadsData = {
  "range": "October 2025 – July 2026",
  "totals": {
    "leads": 2066,
    "customers": 90,
    "convRate": 4.4,
    "customersWithPremium": 30,
    "avgCustomerPremium": 4218,
    "totalCustomerPremium": 126533
  },
  "bySource": [
    {
      "source": "Organic",
      "leads": 1678,
      "customers": 89,
      "customerPremium": 106838,
      "allPremium": 196134,
      "convRate": 5.3
    },
    {
      "source": "Paid Ads",
      "leads": 348,
      "customers": 0,
      "customerPremium": 0,
      "allPremium": 2683,
      "convRate": 0
    },
    {
      "source": "Unknown",
      "leads": 32,
      "customers": 1,
      "customerPremium": 19695,
      "allPremium": 39687,
      "convRate": 3.1
    },
    {
      "source": "Email",
      "leads": 7,
      "customers": 0,
      "customerPremium": 0,
      "allPremium": 0,
      "convRate": 0
    },
    {
      "source": "Direct / Other",
      "leads": 1,
      "customers": 0,
      "customerPremium": 0,
      "allPremium": 0,
      "convRate": 0
    }
  ],
  "byMonth": [
    {
      "key": "2025-10",
      "label": "October 2025",
      "sortKey": 202510,
      "total": 32,
      "organic": 0,
      "paidAds": 0,
      "other": 32,
      "customers": 1,
      "organicCustomers": 0,
      "paidCustomers": 0,
      "paidPremium": 0,
      "organicPremium": 0
    },
    {
      "key": "2026-03",
      "label": "March 2026",
      "sortKey": 202603,
      "total": 173,
      "organic": 120,
      "paidAds": 50,
      "other": 3,
      "customers": 4,
      "organicCustomers": 4,
      "paidCustomers": 0,
      "paidPremium": 0,
      "organicPremium": 1430
    },
    {
      "key": "2026-04",
      "label": "April 2026",
      "sortKey": 202604,
      "total": 265,
      "organic": 220,
      "paidAds": 45,
      "other": 0,
      "customers": 17,
      "organicCustomers": 17,
      "paidCustomers": 0,
      "paidPremium": 0,
      "organicPremium": 54027
    },
    {
      "key": "2026-05",
      "label": "May 2026",
      "sortKey": 202605,
      "total": 199,
      "organic": 175,
      "paidAds": 23,
      "other": 1,
      "customers": 7,
      "organicCustomers": 7,
      "paidCustomers": 0,
      "paidPremium": 0,
      "organicPremium": 30383
    },
    {
      "key": "2026-06",
      "label": "June 2026",
      "sortKey": 202606,
      "total": 215,
      "organic": 185,
      "paidAds": 30,
      "other": 0,
      "customers": 9,
      "organicCustomers": 9,
      "paidCustomers": 0,
      "paidPremium": 0,
      "organicPremium": 20998
    },
    {
      "key": "2026-07",
      "label": "July 2026",
      "sortKey": 202607,
      "total": 77,
      "organic": 63,
      "paidAds": 13,
      "other": 1,
      "customers": 0,
      "organicCustomers": 0,
      "paidCustomers": 0,
      "paidPremium": 0,
      "organicPremium": 0
    }
  ],
  "byInterest": [
    {
      "interest": "Other",
      "leads": 1437
    },
    {
      "interest": "IBC",
      "leads": 856
    },
    {
      "interest": "Whole life",
      "leads": 298
    },
    {
      "interest": "IUL",
      "leads": 129
    }
  ],
  "byAgent": [
    {
      "agent": "Denise Boisvert",
      "leads": 622,
      "customers": 16
    },
    {
      "agent": "Barry  Brooksby",
      "leads": 553,
      "customers": 71
    },
    {
      "agent": "Unassigned",
      "leads": 374,
      "customers": 2
    },
    {
      "agent": "Jason Herring",
      "leads": 302,
      "customers": 1
    },
    {
      "agent": "Steven Gibbs",
      "leads": 194,
      "customers": 0
    },
    {
      "agent": "Abel Salazar",
      "leads": 17,
      "customers": 0
    },
    {
      "agent": "Rachael Katz",
      "leads": 3,
      "customers": 0
    },
    {
      "agent": "Erik Hayton",
      "leads": 1,
      "customers": 0
    }
  ]
};
